- name: Declare a Variable at play level
  hosts: all
  connection: local
  vars:
    URL: ansible.example.com
  tasks:
    - name: Access a Variable
      ansible.builtin.debug:
        msg: URL == {{URL}}



