- name: Declare a Variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access a Variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: Declare a Variable in another file
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: Access a Variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

## vars_files can also be declared on task level

- name: Declare a Variable at task level
  hosts: all
  connection: local
  tasks:
    - name: Declare and Access a Variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task.example.com

- name: Declare a Variable from inventory file
  hosts: all
  connection: local
  tasks:
    - name: Access Variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: Access a fact
  hosts: all
  connection: local
  tasks:
    - name: Access fact
      ansible.builtin.debug:
        msg: Ansible host name == {{ansible_fqdn}}

- name: Register a variable
  hosts: all
  connection: local
  tasks:
    - name: Run a shell command
      ansible.builtin.shell: uptime
      register: out
    - name: Print out
      ansible.builtin.debug:
        msg: "{{out.stdout}}"





