- name: Demo on Conditions
  hosts: all
  vars:
    a: 100
    b: false
  tasks:
    - name: String conditions
      debug:
        msg: fruit name is apple
      when: fruit_name == "apple"
    - name: Numerical Conditions
      debug:
        msg: a is greater than 10
      when: a > 10
    - name: Boolean Conditions
      debug:
        msg: b is true
      when: b
      
  

